import React,{useEffect,useState}from'react';import{createRoot}from'react-dom/client';import{PieChart,Pie,Cell,Tooltip,ResponsiveContainer,BarChart,Bar,XAxis,YAxis}from'recharts';import'./styles.css';
const API=import.meta.env.VITE_API_URL||'http://localhost:10000/api';
async function api(path,o={}){const r=await fetch(API+path,{credentials:'include',headers:{'Content-Type':'application/json',...(o.headers||{})},...o});if(!r.ok)throw Error((await r.json().catch(()=>({error:'Request failed'}))).error||'Request failed');return r.json()}
function Login({ok}){const[e,setE]=useState(''),[p,setP]=useState(''),[x,setX]=useState('');return <div className="login"><div className="loginCard"><div className="logo">DSA</div><h1>Private Training Hub</h1><p>Admin sign in</p><input placeholder="Email" value={e} onChange={a=>setE(a.target.value)}/><input type="password" placeholder="Password" value={p} onChange={a=>setP(a.target.value)}/><button onClick={async()=>{try{await api('/auth/login',{method:'POST',body:JSON.stringify({email:e,password:p})});ok()}catch(a){setX(a.message)}}}>Sign in</button>{x&&<div className="error">{x}</div>}</div></div>}
const nav=[['dashboard','🏆 Dashboard'],['daily','📅 Daily Plan'],['problems','✏️ All Problems'],['completed','✅ Completed'],['remaining','⏳ Remaining'],['sessions','📚 Sessions'],['audit','⚠️ Audit'],['guide','ℹ️ Guide']];
function App(){const[a,setA]=useState(false),[v,setV]=useState('dashboard'),[ps,setPs]=useState([]),[d,setD]=useState(),[err,setErr]=useState('');async function load(){try{const[x,y]=await Promise.all([api('/problems'),api('/dashboard')]);setPs(x);setD(y)}catch(e){if(e.message.includes('Authentication'))setA(false);else setErr(e.message)}}useEffect(()=>{api('/auth/me').then(()=>{setA(true);load()}).catch(()=>setA(false))},[]);async function upd(p,b){try{await api('/problems/'+p.problemNumber+'/progress',{method:'PUT',body:JSON.stringify({...p.progress,...b})});await load()}catch(e){setErr(e.message)}}if(!a)return <Login ok={()=>{setA(true);load()}}/>;let list=v==='completed'?ps.filter(p=>p.progress.status==='Done'):v==='remaining'?ps.filter(p=>p.progress.status!=='Done'):ps;return <div className="layout"><aside><div className="brand">DSA <small>Training Hub</small></div>{nav.map(n=><button className={v===n[0]?'active':''} onClick={()=>setV(n[0])} key={n[0]}>{n[1]}</button>)}<button className="logout" onClick={async()=>{await api('/auth/logout',{method:'POST'});setA(false)}}>🔒 Logout</button></aside><main><header><small>05 Oct 2026 → 04 Jan 2027</small><h1>{nav.find(n=>n[0]===v)[1]}</h1></header>{err&&<div className="error">{err}</div>}{v==='dashboard'&&<Dashboard d={d}/>} {['problems','completed','remaining'].includes(v)&&<Problems list={list} editable={v==='problems'} upd={upd}/>} {v==='daily'&&<Daily ps={ps}/>} {v==='sessions'&&<Sessions ps={ps}/>} {v==='audit'&&<Audit ps={ps}/>} {v==='guide'&&<Guide/>}</main></div>}
function Dashboard({d}){if(!d)return <div className="card">Loading…</div>;return <><div className="stats">{[['🎯 Total',d.total],['✅ Completed',d.completed],['⏳ Remaining',d.remaining],['🔥 Progress',d.progress.toFixed(1)+'%']].map(x=><div className="card stat"><span>{x[0]}</span><b>{x[1]}</b></div>)}</div><div className="grid"><div className="card chart"><h2>Completed vs Remaining</h2><ResponsiveContainer width="100%" height={250}><PieChart><Pie data={[{n:'Completed',v:d.completed},{n:'Remaining',v:d.remaining}]} dataKey="v" nameKey="n" innerRadius={60} outerRadius={90}><Cell fill="#6d5dfc"/><Cell fill="#e5e7eb"/></Pie><Tooltip/></PieChart></ResponsiveContainer></div><div className="card chart"><h2>Session progress</h2><ResponsiveContainer width="100%" height={250}><BarChart data={Object.entries(d.sessionProgress).map(([s,x])=>({s:'S'+s,done:x.done,total:x.total}))}><XAxis dataKey="s"/><YAxis/><Tooltip/><Bar dataKey="done" fill="#6d5dfc"/></BarChart></ResponsiveContainer></div></div></>}
function Problems({list,editable,upd}){return <div className="card table"><div className="scroll"><table><thead><tr><th>#</th><th>Date</th><th>Session</th><th>Difficulty</th><th>LC</th><th>Problem</th><th>Status</th><th>Notes</th><th>Revision</th></tr></thead><tbody>{list.map(p=><tr className={p.progress.status==='Done'?'done':''}><td>{p.problemNumber}</td><td>{p.plannedDate}</td><td>S{p.sessionNumber}<small>{p.sessionTopic}</small></td><td className={p.difficulty.toLowerCase()}>{p.difficulty}</td><td>{p.lcNumber}</td><td>{p.problemName}</td><td>{editable?<select value={p.progress.status} onChange={e=>upd(p,{status:e.target.value})}><option>Not Started</option><option>In Progress</option><option>Done</option></select>:p.progress.status}</td><td>{editable?<input value={p.progress.notes||''} onChange={e=>upd(p,{notes:e.target.value})}/>:p.progress.notes||'—'}</td><td>{p.progress.revisionNeeded||'No'}</td></tr>)}</tbody></table></div></div>}
function Daily({ps}){const m={};ps.forEach(p=>(m[p.plannedDate]??=[]).push(p));return <div className="card table"><div className="scroll"><table><thead><tr><th>Date</th><th>Day</th><th>Target</th><th>Problem #s</th><th>Names</th><th>Done</th></tr></thead><tbody>{Object.entries(m).map(([d,a])=><tr><td>{d}</td><td>{new Date(d+'T00:00:00').toLocaleDateString(undefined,{weekday:'long'})}</td><td>{a.length}</td><td>{a.map(p=>'#'+p.problemNumber).join(', ')}</td><td>{a.map(p=>p.problemName).join('; ')}</td><td>{a.filter(p=>p.progress.status==='Done').length}</td></tr>)}</tbody></table></div></div>}
function Sessions({ps}){const m={};ps.forEach(p=>{m[p.sessionNumber]??={topic:p.sessionTopic,t:0,d:0};m[p.sessionNumber].t++;if(p.progress.status==='Done')m[p.sessionNumber].d++});return <div className="sessions">{Object.entries(m).map(([s,x])=><div className="card"><h3>Session {s}</h3><p>{x.topic}</p><b>{x.d}/{x.t}</b><div className="progress"><span style={{width:x.d/x.t*100+'%'}}/></div></div>)}</div>}
function Audit({ps}){const m={};ps.forEach(p=>(m[p.lcNumber]??=[]).push(p.problemNumber));return <div className="card"><h2>Audit</h2><p>Expected = 207 · Extracted = {ps.length} · Scheduled = {ps.filter(p=>p.plannedDate).length} · Unscheduled = 0 · Days = 92</p><h3>PDF duplicate LC numbers</h3>{Object.entries(m).filter(([,x])=>x.length>1).map(([lc,x])=><p>LC {lc}: #{x.join(', #')} — Duplicate in PDF — intentional curriculum repetition.</p>)}</div>}
function Guide(){return <div className="card"><h2>Guide</h2><p>Progress is stored in MongoDB through the Render API. The browser no longer owns the source of truth.</p><p>Set <code>VITE_API_URL</code> on Vercel to your Render API URL. Configure Atlas only through Render's <code>MONGODB_URI</code>.</p></div>}
createRoot(document.getElementById('root')).render(<App/>);
